### PR TITLE
[ADD] modules for BBA structured communication on supplier invoice

### PR DESCRIPTION
**Pull request by vvrossem**
- [`account_supplier_invoice_number`](https://github.com/Noviat/noviat-apps/tree/12.0/account_supplier_invoice_number):
  adds the 'Supplier Invoice Number' field to a supplier invoice

- [`l10n_be_invoice_bba_customer_supplier`](https://github.com/Noviat/noviat-apps/tree/12.0/l10n_be_invoice_bba_customer_supplier):
  an alternative to the 'l10n_be_invoice_bba' module of the standard addons

Both modules were found on https://github.com/Noviat/noviat-apps/tree/12.0, copied and pre-commited in coopiteasy/cie-imported-modules

### CODE REVIEW

**Comment by houssine78** [comment]
@vvrossem this module seems to be incompatible with easy my coop that is using the standard bba communication module.

**Comment by houssine78** [comment]
this [module](https://github.com/coopiteasy/addons/pull/159) is simpler and allows to stick to the standard.

**Comment by robinkeunen** [comment]
@houssine78 why not forking the repo and add it to gitaggregator rather than copying?

**Comment by houssine78** [comment]
@robinkeunen this is the purpose of this repo copying module from repo that we don't want to fork.

anyway this PR has been closed. I developped a module far more simpler than the one of Noviat

**Pull request closed without merging**
